name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.aws }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRET_ACCESSKEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
